In [81]:
import pandas as pd
import numpy as np
np.set_printoptions(linewidth=1000)

In [98]:
df = pd.read_csv('movie_reviews.csv', index_col=0)

In [99]:
# load csv with column headers and row headers
df.head()

Matrix  Inception  Harry Potter  Sholay  Titanic  Hangover  \
Sandeep Giri       9          7           6.5       6        8         6   
GK                 8          9           8.0       5        6         8   
sneha              7          7           5.0       7        8         5   
Deep               8          7           9.0       6        6         8   
Tanya              9          5           9.5       5        5         5   

              Sarfarosh  Joker  Bahubali  Jab We Met  
Sandeep Giri          7    7.0       7.0         6.5  
GK                    3    0.0       4.0         5.0  
sneha                 9    6.0       7.0         9.0  
Deep                  4    8.0       6.0         5.0  
Tanya                 5    5.0       7.5         7.0

In [100]:
df.loc['GK']

Matrix          8.0
Inception       9.0
Harry Potter    8.0
Sholay          5.0
Titanic         6.0
Hangover        8.0
Sarfarosh       3.0
Joker           0.0
Bahubali        4.0
Jab We Met      5.0
Name: GK, dtype: float64

In [101]:
df['Matrix']

Sandeep Giri    9
GK              8
sneha           7
Deep            8
Tanya           9
Nigam           6
Supriya         8
Indu            6
Simar           6
Anubhav         8
Name: Matrix, dtype: int64

In [102]:
data = df.to_numpy()

In [12]:
data.shape

(10, 10)

In [13]:
data[0]

array([9. , 7. , 6.5, 6. , 8. , 6. , 7. , 7. , 7. , 6.5])

In [14]:
data[1]

array([8., 9., 8., 5., 6., 8., 3., 0., 4., 5.])

In [ ]:
# data = data[1:]

In [24]:
data.shape

(9, 10)

In [103]:
data

array([[9. , 7. , 6.5, 6. , 8. , 6. , 7. , 7. , 7. , 6.5],
       [8. , 9. , 8. , 5. , 6. , 8. , 3. , 0. , 4. , 5. ],
       [7. , 7. , 5. , 7. , 8. , 5. , 9. , 6. , 7. , 9. ],
       [8. , 7. , 9. , 6. , 6. , 8. , 4. , 8. , 6. , 5. ],
       [9. , 5. , 9.5, 5. , 5. , 5. , 5. , 5. , 7.5, 7. ],
       [6. , 5. , 5. , 9. , 7. , 6. , 7. , 6. , 9. , 9. ],
       [8. , 9. , 9. , 5. , 7. , 7. , 7. , 0. , 8. , 8. ],
       [6. , 9. , 9. , 5. , 9. , 4. , 4. , 8. , 9. , 6. ],
       [6. , 8. , 8. , 9. , 9. , 5. , 9. , 7.2, 9. , 9. ],
       [8. , 8. , 8. , 6. , 6. , 6. , 7. , 8. , 8. , 6. ]])

In [104]:
vnorms = np.linalg.vector_norm(data, axis=1)
vnorms

array([22.30470802, 19.59591794, 22.53885534, 21.70253441, 20.65187643, 22.3383079 , 22.93468988, 22.737634  , 25.4133823 , 22.64950331])

In [105]:
data 

array([[9. , 7. , 6.5, 6. , 8. , 6. , 7. , 7. , 7. , 6.5],
       [8. , 9. , 8. , 5. , 6. , 8. , 3. , 0. , 4. , 5. ],
       [7. , 7. , 5. , 7. , 8. , 5. , 9. , 6. , 7. , 9. ],
       [8. , 7. , 9. , 6. , 6. , 8. , 4. , 8. , 6. , 5. ],
       [9. , 5. , 9.5, 5. , 5. , 5. , 5. , 5. , 7.5, 7. ],
       [6. , 5. , 5. , 9. , 7. , 6. , 7. , 6. , 9. , 9. ],
       [8. , 9. , 9. , 5. , 7. , 7. , 7. , 0. , 8. , 8. ],
       [6. , 9. , 9. , 5. , 9. , 4. , 4. , 8. , 9. , 6. ],
       [6. , 8. , 8. , 9. , 9. , 5. , 9. , 7.2, 9. , 9. ],
       [8. , 8. , 8. , 6. , 6. , 6. , 7. , 8. , 8. , 6. ]])

In [106]:
arr = np.array([[1,2], [3, 4], [6, 7]]) 
vnorm = np.linalg.norm(arr, axis=1)
vnorm


array([2.23606798, 5.        , 9.21954446])

In [45]:
vnorm = vnorm.reshape(-1, 1)

In [44]:
vnorm

array([[2.23606798],
       [5.        ],
       [9.21954446]])

In [39]:
arr / vnorm

array([[0.4472136 , 0.89442719],
       [0.6       , 0.8       ],
       [0.65079137, 0.7592566 ]])

In [107]:
def to_uv(v):
    vnorm = np.linalg.norm(v, axis=1)
    vnorm = vnorm.reshape(-1, 1)
    return v / vnorm

In [108]:
udata = to_uv(data)

In [109]:
udata

array([[0.40350226, 0.31383509, 0.2914183 , 0.2690015 , 0.35866867, 0.2690015 , 0.31383509, 0.31383509, 0.31383509, 0.2914183 ],
       [0.40824829, 0.45927933, 0.40824829, 0.25515518, 0.30618622, 0.40824829, 0.15309311, 0.        , 0.20412415, 0.25515518],
       [0.31057478, 0.31057478, 0.22183913, 0.31057478, 0.3549426 , 0.22183913, 0.39931043, 0.26620695, 0.31057478, 0.39931043],
       [0.36862054, 0.32254297, 0.41469811, 0.27646541, 0.27646541, 0.36862054, 0.18431027, 0.36862054, 0.27646541, 0.23038784],
       [0.43579575, 0.24210875, 0.46000663, 0.24210875, 0.24210875, 0.24210875, 0.24210875, 0.24210875, 0.36316313, 0.33895225],
       [0.26859689, 0.22383074, 0.22383074, 0.40289533, 0.31336304, 0.26859689, 0.31336304, 0.26859689, 0.40289533, 0.40289533],
       [0.34881658, 0.39241865, 0.39241865, 0.21801036, 0.3052145 , 0.3052145 , 0.3052145 , 0.        , 0.34881658, 0.34881658],
       [0.2638797 , 0.39581955, 0.39581955, 0.21989975, 0.39581955, 0.1759198 , 0.1759198 , 0.351

In [56]:
data

array([[8. , 9. , 8. , 5. , 6. , 8. , 3. , 0. , 4. , 5. ],
       [7. , 7. , 5. , 7. , 8. , 5. , 9. , 6. , 7. , 9. ],
       [8. , 7. , 9. , 6. , 6. , 8. , 4. , 8. , 6. , 5. ],
       [9. , 5. , 9.5, 5. , 5. , 5. , 5. , 5. , 7.5, 7. ],
       [6. , 5. , 5. , 9. , 7. , 6. , 7. , 6. , 9. , 9. ],
       [8. , 9. , 9. , 5. , 7. , 7. , 7. , 0. , 8. , 8. ],
       [6. , 9. , 9. , 5. , 9. , 4. , 4. , 8. , 9. , 6. ],
       [6. , 8. , 8. , 9. , 9. , 5. , 9. , 7.2, 9. , 9. ],
       [8. , 8. , 8. , 6. , 6. , 6. , 7. , 8. , 8. , 6. ]])

In [57]:
udata

array([[0.40824829, 0.45927933, 0.40824829, 0.25515518, 0.30618622,
        0.40824829, 0.15309311, 0.        , 0.20412415, 0.25515518],
       [0.31057478, 0.31057478, 0.22183913, 0.31057478, 0.3549426 ,
        0.22183913, 0.39931043, 0.26620695, 0.31057478, 0.39931043],
       [0.36862054, 0.32254297, 0.41469811, 0.27646541, 0.27646541,
        0.36862054, 0.18431027, 0.36862054, 0.27646541, 0.23038784],
       [0.43579575, 0.24210875, 0.46000663, 0.24210875, 0.24210875,
        0.24210875, 0.24210875, 0.24210875, 0.36316313, 0.33895225],
       [0.26859689, 0.22383074, 0.22383074, 0.40289533, 0.31336304,
        0.26859689, 0.31336304, 0.26859689, 0.40289533, 0.40289533],
       [0.34881658, 0.39241865, 0.39241865, 0.21801036, 0.3052145 ,
        0.3052145 , 0.3052145 , 0.        , 0.34881658, 0.34881658],
       [0.2638797 , 0.39581955, 0.39581955, 0.21989975, 0.39581955,
        0.1759198 , 0.1759198 , 0.3518396 , 0.39581955, 0.2638797 ],
       [0.23609608, 0.31479478, 0.3147947

In [110]:
sim_mat = udata @ udata.T

/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/1890260315.py:1: RuntimeWarning: divide by zero encountered in matmul
  sim_mat = udata @ udata.T
/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/1890260315.py:1: RuntimeWarning: overflow encountered in matmul
  sim_mat = udata @ udata.T
/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/1890260315.py:1: RuntimeWarning: invalid value encountered in matmul
  sim_mat = udata @ udata.T


In [66]:
from pprint import pprint

In [111]:
pprint(sim_mat)

array([[1.        , 0.90257823, 0.98066013, 0.97093658, 0.96768786, 0.96337289, 0.93538958, 0.96124215, 0.97541084, 0.98972554],
       [0.90257823, 1.        , 0.86489999, 0.91704055, 0.90933245, 0.84525128, 0.96345051, 0.87529354, 0.86546436, 0.89447089],
       [0.98066013, 0.86489999, 1.        , 0.92200703, 0.93668834, 0.98117126, 0.93050851, 0.93271888, 0.98849742, 0.96573146],
       [0.97093658, 0.91704055, 0.92200703, 1.        , 0.96497517, 0.9220337 , 0.908103  , 0.95650286, 0.93665893, 0.98056842],
       [0.96768786, 0.90933245, 0.93668834, 0.96497517, 1.        , 0.93642706, 0.94691295, 0.94553624, 0.94601335, 0.97273198],
       [0.96337289, 0.84525128, 0.98117126, 0.9220337 , 0.93642706, 1.        , 0.91153581, 0.92337327, 0.98327974, 0.95463681],
       [0.93538958, 0.96345051, 0.93050851, 0.908103  , 0.94691295, 0.91153581, 1.        , 0.90895043, 0.92991648, 0.92981292],
       [0.96124215, 0.87529354, 0.93271888, 0.95650286, 0.94553624, 0.92337327, 0.90895043, 1.   

In [68]:
sim_mat[0][1], sim_mat[1][0]

(np.float64(0.8648999949776485), np.float64(0.8648999949776485))

In [112]:
np.fill_diagonal(sim_mat, 0)


In [113]:
sim_mat

array([[0.        , 0.90257823, 0.98066013, 0.97093658, 0.96768786, 0.96337289, 0.93538958, 0.96124215, 0.97541084, 0.98972554],
       [0.90257823, 0.        , 0.86489999, 0.91704055, 0.90933245, 0.84525128, 0.96345051, 0.87529354, 0.86546436, 0.89447089],
       [0.98066013, 0.86489999, 0.        , 0.92200703, 0.93668834, 0.98117126, 0.93050851, 0.93271888, 0.98849742, 0.96573146],
       [0.97093658, 0.91704055, 0.92200703, 0.        , 0.96497517, 0.9220337 , 0.908103  , 0.95650286, 0.93665893, 0.98056842],
       [0.96768786, 0.90933245, 0.93668834, 0.96497517, 0.        , 0.93642706, 0.94691295, 0.94553624, 0.94601335, 0.97273198],
       [0.96337289, 0.84525128, 0.98117126, 0.9220337 , 0.93642706, 0.        , 0.91153581, 0.92337327, 0.98327974, 0.95463681],
       [0.93538958, 0.96345051, 0.93050851, 0.908103  , 0.94691295, 0.91153581, 0.        , 0.90895043, 0.92991648, 0.92981292],
       [0.96124215, 0.87529354, 0.93271888, 0.95650286, 0.94553624, 0.92337327, 0.90895043, 0.   

# For every person find most similar buddy

In [115]:
bud_idx = sim_mat.argmax(axis=1)
bud_idx

array([9, 6, 8, 9, 9, 8, 1, 9, 2, 0])

In [123]:
p = df.index

In [124]:
buddy = df.index[[9, 6, 8, 9, 9, 8, 1, 9, 2, 0]]

In [126]:
list(zip(p, buddy))

[('Sandeep Giri', 'Anubhav'),
 ('GK', 'Supriya '),
 ('sneha', 'Simar'),
 ('Deep', 'Anubhav'),
 ('Tanya', 'Anubhav'),
 ('Nigam', 'Simar'),
 ('Supriya ', 'GK'),
 ('Indu', 'Anubhav'),
 ('Simar', 'sneha'),
 ('Anubhav', 'Sandeep Giri')]

In [128]:
import pandas as pd
import numpy as np
np.set_printoptions(linewidth=1000)

df = pd.read_csv('movie_reviews.csv', index_col=0)
data = df.to_numpy()

def to_uv(v, axis):
    vnorm = np.linalg.norm(v, axis=axis)
    vnorm = vnorm.reshape(-1, 1)
    return v / vnorm

udata = to_uv(data, axis = 1)

sim_mat = udata @ udata.T
# For every person find most similar buddy
bud_idx = sim_mat.argmax(axis=1)
buddy = df.index[[9, 6, 8, 9, 9, 8, 1, 9, 2, 0]]
p = df.index
print(list(zip(p, buddy)))


[('Sandeep Giri', 'Anubhav'), ('GK', 'Supriya '), ('sneha', 'Simar'), ('Deep', 'Anubhav'), ('Tanya', 'Anubhav'), ('Nigam', 'Simar'), ('Supriya ', 'GK'), ('Indu', 'Anubhav'), ('Simar', 'sneha'), ('Anubhav', 'Sandeep Giri')]


/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/4288156565.py:15: RuntimeWarning: divide by zero encountered in matmul
  sim_mat = udata @ udata.T
/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/4288156565.py:15: RuntimeWarning: overflow encountered in matmul
  sim_mat = udata @ udata.T
/var/folders/xg/0b5tly_55_v3g39k5qx0jc580000gn/T/ipykernel_54119/4288156565.py:15: RuntimeWarning: invalid value encountered in matmul
  sim_mat = udata @ udata.T


In [ ]:
# We convert every product and every user into a vector -> 
# Some characterstics -> age, location etc
# Their behaviour characters: their spendings habits...
# their description -> llm -> embeddings 


In [ ]:
# Problem: Scale
# 10 million users -> 10,000 products.

# 10**3 * 10**6 * 10** 6 => 10**15

# Reduce the operations over by optimization such sharding.
# *Use the PCA  or other dimensionality reduction technique to make vector smaller*
# MLLib by Apache Spark
# GPUs


In [129]:
# Problem: Code Start

# Can I find the similarity of a movie which is newly released?
# We need more characterstics of moview instead of just ratings by people

# Can a new user get any recommendations?
# Solution: top k movies in that region.
# 
# 0. Server -> regex -> product <> user data
# 1. Top k products
# 2. prepare the recormmendation for frequent users
# 3. Model based
