In [34]:
import numpy as np

x = np.array([171, 173, 163, 162, 160])
y = np.array([1, 1, 0, 0, 0])

def lin_error(m, c, x, y):
    return np.average(((m*x + c) - y)**2)

def sigm(x):
    return np.exp(x)/(np.exp(x) + 1)

def lin_error_sigmoid(m, c, x, y):
    return np.average((sigm(m*x + c) - y)**2)


In [35]:
lin_error(.1, .5, x, y)

np.float64(278.236)

In [36]:
lin_error(.101, .5, x, y)

np.float64(283.7950366000001)

In [37]:
lin_error(.1, .501, x, y)

np.float64(278.269361)

In [38]:
eps = 1e-8
def grad(f, m, c, x, y): # idx = 0, m
    e1 = f(m, c, x, y)
    e1m = f(m + eps, c, x, y)
    e1c = f(m, c + eps, x , y)
    gradm = (e1m - e1)/eps
    gradc = (e1c - e1)/eps
    return gradm, gradc

In [39]:
def find_m_c():
    m = 0.12
    c = .3
    eta = .00001
    epoch = 100
    for i in range(epoch):
        gm, gc = grad(lin_error, m, c, x, y)
        m = m - eta * gm
        c = c - eta * gc
        print(i, lin_error(m, c, x, y), f"m:{m}, c:{c}")

In [40]:
find_m_c()

0 79.42750741392021 m:0.05434135723191502, c:0.299604079960136
1 16.247819258001023 m:0.024818079528467926, c:0.2994258919571166
2 3.4739408103447653 m:0.011542997172422237, c:0.29934560668535254
3 0.8912762805886238 m:0.005573883668943285, c:0.29930934319403163
4 0.36910493539469796 m:0.002889884587955354, c:0.2992928740086828
5 0.2635307637037517 m:0.0016830307009628666, c:0.29928530529375025
6 0.24218550004438502 m:0.0011403722252521999, c:0.2992817386577082
7 0.23786987323159164 m:0.0008963679007288829, c:0.29927997154855474
8 0.23699733496594014 m:0.0007866528239274186, c:0.29927901359311754
9 0.23682092270297045 m:0.0007373206412829504, c:0.2992784194720041
10 0.23678525141003043 m:0.0007151395075476398, c:0.29927798894827634
11 0.23677803374776082 m:0.0007051667890910431, c:0.29927763198581675
12 0.23677656810433606 m:0.0007006835604138552, c:0.29927730810003744
13 0.23677626504950408 m:0.0006986686699371682, c:0.2992769990871111
14 0.23677619688264265 m:0.0006977636628401275, c

In [41]:
m=0.0006971748350202913
c=0.29925145909057677

print(m*x + c)
print(y)

[0.41846836 0.41986271 0.41289096 0.41219378 0.41079943]
[1 1 0 0 0]


In [50]:
def find_m_c():
    m = 0.12
    c = .3
    eta = .1
    epoch = 100
    for i in range(epoch):
        gm, gc = grad(lin_error_sigmoid, m, c, x, y)
        m = m - eta * gm
        c = c - eta * gc
        print(i, lin_error_sigmoid(m, c, x, y), f"m:{m}, c:{c}")

In [51]:
find_m_c()

0 0.599999996623038 m:0.11999994559907179, c:0.3
1 0.5999999966230088 m:0.1199998923083666, c:0.3
2 0.5999999966229785 m:0.11999983679721538, c:0.29999999888977696
3 0.599999996622949 m:0.11999978239628717, c:0.29999999777955394
4 0.5999999966229194 m:0.11999972799535896, c:0.29999999777955394
5 0.5999999966228902 m:0.11999967470465378, c:0.29999999777955394
6 0.59999999662286 m:0.11999961919350255, c:0.29999999777955394
7 0.5999999966228302 m:0.11999956479257434, c:0.29999999777955394
8 0.5999999966228007 m:0.11999951039164614, c:0.2999999966693309
9 0.599999996622771 m:0.11999945599071793, c:0.2999999966693309
10 0.5999999966227418 m:0.11999940270001275, c:0.2999999966693309
11 0.5999999966227116 m:0.11999934718886152, c:0.2999999966693309
12 0.5999999966226826 m:0.11999929389815633, c:0.2999999966693309
13 0.5999999966226529 m:0.11999923949722813, c:0.2999999966693309
14 0.5999999966226233 m:0.11999918509629992, c:0.2999999966693309
15 0.5999999966225941 m:0.11999913180559474, c:0.2

In [45]:
m=0.11999999946953543
c=0.2999999999961142

print(sigm(m*x + c))
print(y)

[1. 1. 1. 1. 1.]
[1 1 0 0 0]
